provider:
  name: faas
  gateway: https://gateway.fn.rnd.dev
functions:
  youtubedl:
    lang: Dockerfile
    handler: ./
    image: randomnerd/faas-youtubedl:latest
    environment:
      read_timeout: 300s
      write_timeout: 300s
    labels: 
      com.openfaas.ui.ext: "mp4"
